# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QMainWindow, QTextEdit, QVBoxLayout, QWidget, QScrollArea

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # label which are used to show the picure
        self.label_InputImage = QtWidgets.QLabel(self.centralwidget)
        self.label_InputImage.setGeometry(QtCore.QRect(40, 40, 400, 400))
        self.label_InputImage.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_InputImage.setObjectName("label_InputImage")
        self.label_InputImage.setAlignment(Qt.AlignCenter)

        self.label_OutputImage = QtWidgets.QLabel(self.centralwidget)
        self.label_OutputImage.setGeometry(QtCore.QRect(500, 40, 400, 400))
        self.label_OutputImage.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_OutputImage.setObjectName("label_OutputImage")
        self.label_OutputImage.setAlignment(Qt.AlignCenter)

        self.label_Output = QtWidgets.QLabel(self.centralwidget)
        self.label_Output.setGeometry(QtCore.QRect(640, 480, 140, 30))
        self.label_Output.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Output.setObjectName("label_Output")
        self.label_Output.setAlignment(Qt.AlignCenter)

        self.text_onnxpath = QtWidgets.QTextEdit(self.centralwidget)
        self.text_onnxpath.setGeometry(QtCore.QRect(965, 130, 400, 30))
        self.text_onnxpath.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.text_onnxpath.setObjectName("text onnx path")

        # button input
        self.pushButton_Input = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Input.setGeometry(QtCore.QRect(180, 480, 140, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_Input.setFont(font)
        self.pushButton_Input.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_Input.setObjectName("pushButton_Input")
        
        # button onnx
        self.pushButton_Onnx = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Onnx.setGeometry(QtCore.QRect(965, 90, 140, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_Onnx.setFont(font)
        self.pushButton_Onnx.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_Onnx.setObjectName("pushButton_Onnx")
        
        
        # button run
        self.pushButton_Run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Run.setGeometry(QtCore.QRect(1000, 500, 140, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_Run.setFont(font)
        self.pushButton_Run.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_Run.setObjectName("pushButton_Run")
        MainWindow.setCentralWidget(self.centralwidget)

        # button Write
        ## 图像保存
        self.pushButton_Write = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Write.setGeometry(QtCore.QRect(1000, 450, 140, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_Write.setFont(font)
        self.pushButton_Write.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_Write.setObjectName("pushButton_Write")
        ## 参数保存
        self.pushButton_Result_Write = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Result_Write.setGeometry(QtCore.QRect(1160, 450, 140, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_Result_Write.setFont(font)
        self.pushButton_Result_Write.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_Result_Write.setObjectName("pushButton_Result_Write")

        # 滑动条 QtCore.QRect(965, 130, 200, 31)
        ## 创建一个 QTextEdit 控件
        self.text_edit = QTextEdit(self.centralwidget)
        self.text_edit.setFixedHeight(250)  # 设置文本框高度
        self.text_edit.setFixedWidth(400)  # 设置文本框宽度
        self.text_edit.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        ## 创建一个 QScrollArea 控件
        self.scroll_area = QScrollArea(self.centralwidget)
        self.scroll_area.setWidgetResizable(True)  # 设置为可调整大小
        self.scroll_area.setWidget(self.text_edit)  # 设置 QTextEdit 为 QScrollArea
        # self.scroll_area.setGeometry(QtCore.QRect(1000, 250, 200, 100))
        self.scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        # 设置滚动条的位置，放在右下角
        self.scroll_area.setGeometry(QtCore.QRect(965, 180, 400, 250))
        
        MainWindow.setCentralWidget(self.centralwidget)
        # translate
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "主程序界面"))
        # 显示的label
        self.label_InputImage.setText(_translate("MainWindow", "无图像输入"))
        self.label_OutputImage.setText(_translate("MainWindow", "无图像输出"))
        self.label_Output.setText(_translate("MainWindow","输出图像"))
        # 按钮
        self.pushButton_Input.setText(_translate("MainWindow", "请输入检测图像"))
        self.pushButton_Onnx.setText(_translate("MainWindow", "onnx模型"))
        self.pushButton_Run.setText(_translate("MainWindow", "运行"))
        self.pushButton_Write.setText(_translate("MainWindow", "保存"))
        self.pushButton_Result_Write.setText(_translate("MainWindow", "保存检测数据"))
